---
# handlers file for app_stack
- name: Restart app_stack (docker compose)
  community.docker.docker_compose_v2:
    project_src: "/opt/ai_stack"
    state: present # Это перезапустит сервисы, если их конфигурация изменилась
    recreate: smart # Пересоздаст контейнеры, если конфигурация или образ изменились
    # pull: missing # Можно добавить, чтобы подтягивать образы, если они отсутствуют