---
# tasks file for docker role

- name: Добавление официального GPG ключа Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker_install

- name: Добавление репозитория Docker
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  tags: docker_install

- name: Установка Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin # Docker Compose V2
    state: present
    update_cache: yes
  tags: docker_install

- name: Убедиться, что сервис Docker запущен и включен при загрузке
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  tags: docker_service

- name: Добавление пользователя {{ vps_user_name }} в группу docker
  ansible.builtin.user:
    name: "{{ vps_user_name }}"
    groups: docker
    append: yes
  tags: docker_user
  notify: Restart Docker Service # Может потребоваться для применения членства в группе без перезагрузки сессии

# Примечание: Docker Compose V1 (через pip) больше не рекомендуется,
# так как Docker Compose V2 (docker-compose-plugin) устанавливается с Docker Engine.
# Если по какой-то причине потребуется V1:
# - name: Установка Docker Compose (если не используется docker-compose-plugin)
#   ansible.builtin.pip:
#     name: docker-compose
#     state: present
#   when: install_docker_compose_v1 | default(false)